# Generated by Django 4.1.4 on 2022-12-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
        ),
    ]
